java/src/json/ext/Parser.java
java/src/json/ext/Parser.rl

The RuntimeInfo.forRuntime method synchronizes all invocations and
ParserSession#parseString was calling this many times when parsing
large JSON strings. Thus, when running in a heavily multithreaded
environment, threads were spending a large portion of their time
waiting on that synchronization instead of doing work parsing the
JSON.
This fix simply passes in the RuntimeInfo object to the ParserSession
when it's instantiated, since the RuntimeInfo is already known and
we've already incurred the synchronization cost at that time.
Using the test script at
https://gist.github.com/bbrowning/0b89580b03a5f19e7a9f, I get the
following results before and after this fix on my machine:
Before:
$ jruby ~/tmp/json_contention.rb
337.920000 0.570000 338.490000 ( 57.955000)
After:
$ jruby …

Improve JRuby perf. by removing source of multithreaded contention

---

ext/json/ext/generator/generator.c
tests/test_json_generate.rb

The parameter space_before, documented as a string that is put before a : pair delimiter, is never used. 
Script to reproduce the issue:
```ruby
require 'json'
state = JSON::Ext::Generator::State.new( space_before: "bef_delim", space: "aft_delim")
puts JSON.generate({'1' => 2},state)
```
This solves #225 
Link to the issue in the ruby tracker: 
https://bugs.ruby-lang.org/issues/10317

JSON::State is not using the parameter space_before

---

ext/json/ext/fbuffer/fbuffer.h

I fixed to build fail with rb_str_new macro usage. ref. https://github.com/flori/json/issues/229

Support to build with Ruby 2.2.0

---

ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.h
ext/json/ext/parser/parser.rl

Fixes potential memory leaks when wrapper object creation fails after struct allocation.
Merges:
ruby/ruby@cbf902f
ruby/ruby@4d059bf

Potential memory leak

---

lib/json/add/date.rb
lib/json/add/date_time.rb
lib/json/add/exception.rb
lib/json/add/ostruct.rb
lib/json/add/range.rb
lib/json/add/regexp.rb
lib/json/add/struct.rb
lib/json/add/symbol.rb
lib/json/add/time.rb

_(Previously submitted to MRI's bug tracker, as https://bugs.ruby-lang.org/issues/12255)._
This patch removes some comments that otherwise would appear in MRI's docs of the affected core classes.
E.g. for `Exception`
```
$ ri Exception
Descendants of class Exception are used to [...]
[snipped class documentation]
Exception serialization/deserialization        <- does not belong here!
-------------------------------------------
Class methods:
[snip]
```
Or see for example http://docs.ruby-lang.org/en/trunk/Exception.html, where the same comment appears just above the "Public Class Methods" section.

Remove comments from core classes in json/add

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

The parser uses `rb_str_buf_new` to allocate new strings.
`rb_str_buf_new` [has a minimum size of 128 and is not an embedded
string](https://github.com/ruby/ruby/blob/9949407fd90c1c5bfe332141c75db995a9b867aa/string.c#L1119-L1135).  This causes applications that parse JS to allocate extra memory when parsing short strings.
For a real-world example, we can use the mime-types gem.  The mime-types
gem stores all mime types inside a JSON file and parses them when you
require the gem.
Here is a sample program:
```ruby
require 'objspace'
require 'mime-types'
GC.start
GC.start
p ObjectSpace.memsize_of_all String
```
The example program loads the mime-types gem and outputs the total space
used by all strings.  Here are the results of the program before and
after this patch:
** Before **
``` …
```

resize strings after parsing

---

README.md

[Now complies to newest JSON RFC 7159.](https://github.com/chottoda/json/blob/master/CHANGES.md#2015-09-11-200)

(README.md) Now complies to newest JSON RFC 7159.

---

ext/json/ext/generator/generator.c

Suppress a unused-but-set-variable warning by gcc.

Suppress a warning

---

tests/json_common_interface_test.rb

ruby core test suites does not have `assert_raises` method. I replaced these assertions to use `assert_raise`

Fix inconsistency usage for assertion methods

---

tests/json_parser_test.rb

Parsing using a different `decimal_class` is implemented, but tests are lacking. This pull requests tests parsing using BigDecimal as a `decimal_class`.
Note that the tests currently fail due to bug #320.

Actually test BigDecimal parsing.

---

Gemfile
Rakefile
json-java.gemspec

Back-out change of directory of json-java.gemspec.

---

README.md

The example doesn't work OOTB, since this flag is _not enabled_ by default.
(Even with this change in place, I cannot get additions to work with the `Range` class. For custom objects it works though, I tested with the example from the `json_addition_test.rb` - that's where I got the working approach.)

Fixed json_create example to use create_additions = true

---

README.md

I feel that it's more natural this way. What do you think, do you prefer the current style?

README: Fixed code examples to start in the left-most column

---

tests/json_parser_test.rb

It's a backport patch for test preparation.
https://github.com/ruby/ruby/commit/ab8e756de0f88f1841510a4043558c0f4d28c5cc
`test_parse_bigdecimals` needs explicitly a declaration of bigdecimal.

Added missing bigdecimal for its test

---

README.md

Credits to https://stackoverflow.com/a/37489972/227779 which inspired this PR. 😄

README: Added note about json/add/exception

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

This is backport pull-request with some commits from the Ruby core repository.

Backport from Ruby core repository

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

`BigDecimal.new` is no longer available from bigdecimal-1.4.0.
This pull request removes the dependencies that method.

Fix for bigdecimal updates

---

ext/json/ext/generator/generator.c

Currently same as #allow_nan?.

fix JSON::Generator::State#ascii_only? document same as lib/json/pure/generator.rb.

---

README.md

This PR changes the link in the README to the existing rendered documentation.
(RubyForge is closed.)

README: Docs at rubydoc.info, not on rubyforge

---

lib/json/add/bigdecimal.rb
lib/json/add/complex.rb
lib/json/add/rational.rb
lib/json/add/regexp.rb

Below methods are not passing arguments to #to_json.
* BigDecimal#to_json
* Complex#to_json
* Rational#to_json
* Regexp#to_json
But, for example Date#to_json is passing arguments.
```
require "json/add/core"
require "json/add/complex"
puts Date.today.to_json(space: " ") #=> '{"json_class": "Date","y": 2019,"m": 1,"d": 15,"sg": 2299161.0}'
puts 1i.to_json(space: " ")         #=> '{"json_class":"Complex","r":0,"i":1}'
```
We can pass arguments all #to_json in json/add/* after this PR.
```
require "json/add/core"
require "json/add/complex"
puts Date.today.to_json(space: " ") #=> '{"json_class": "Date","y": 2019,"m": 1,"d": 15,"sg": 2299161.0}'
puts 1i.to_json(space: " ")         #=> '{"json_class": "Complex","r": 0,"i": 1}'
```

Pass args all #to_json in json/add/*.

---

json-java.gemspec

The RubyGems property rubyforge_project is removed without a replacement.

Gemspec: Drop EOL'd property rubyforge_project

---

lib/json.rb

This text used to be true in older versions of json, but has not
been true for a number of years (since json version 2 I think).

Remove invalid JSON.generate description from JSON module rdoc

---

ext/json/ext/generator/generator.c

Explanation: currently, stdlib docs list of classes look like this on docs.ruby-lang.org:
This is unnecessary pollution, as `GeneratorMethods`, in fact, is detail of implementation, and every module just contains the same, briefly documented, `to_json` method.
(I am not sure if there is a shorter way to "dedocument" modules for C extension, so far that's the only way I've found)

Add :nodoc: for GeneratorMethods

---

lib/json.rb
lib/json/common.rb

What is here:
* adding docs for (questionable, yet present) "additions" feature;
* cleaning up (both formatting and formulations) docs of `JSON.generate`: current docs are poorly formatted and its documentation shifted more towards (internal) `State` object than just options;
* some other style/formatting cleanups.

Enhance generic JSON and #generate docs

---

.travis.yml

The latest release of JSON (2.3.0) unfortunately broke TruffleRuby 19.3.0, as it used `rb_gc_register_mark_object` which was not yet supported by TruffleRuby: https://github.com/oracle/truffleruby/pull/1856
The TruffleRuby 19.3.1 release fixes it.
It would be useful to test TruffleRuby in CI to notice when it breaks, and if possible avoid breaking it.
I checked and it [fails as expected](https://travis-ci.org/flori/json/jobs/637792223) when using a not-yet-implemented C API function.

Test with TruffleRuby in CI

---

lib/json/pure/generator.rb
lib/json/pure/parser.rb

While reading your documention I noticed two typos in the comments. Thanks for providing this great library!

Spelling and grammar fixes for comments.

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

Use frozen string for hash key

---

lib/json.rb
lib/json/common.rb

Enhancements in json.rb:
* Added JSON types.
* More examples for JSON.parse and JSON.generate.
* Examples for all JSON additions.
* Example custom JSON addition.
Enhancements in common.rb:
* More examples for JSON.generate, its options, and its exceptions.
* More examples for JSON.parse, its options, and its exceptions.
* Example for JSON.pretty_generate.
Not enhanced:  JSON.restore, JSON.dump, JSON.load, JSON.recurse_proc.
If preferred, I can put up a PR with just json.rb.
Also if preferred, I can put up piecemeal PRs for common.rb.

Rdoc enhancements

---

lib/json/common.rb

Added :call-seq: to RDoc for the methods I revised in an earlier PR:
- generate
- parse
- parse!
- pretty_generate
In particular, this adds the return type.

Added :call-seq: to RDoc for some methods

---

CHANGES.md

This is a summary of the changes to v2.3.0 which I hope is accurate.

Update Changes for 2.3.0 [Fixes #397]

---

CHANGES.md

Sorry @hsbt, issue #409 made me realize it's best to make my wording more precise, as `JSON.load` still has default set to true.
Thanks in advance.

Make changes more precise [#424]

---

Rakefile
json_pure.gemspec

The only `json_pure` gemspec is auto-generated by Rakefile. It's inconsistency workflow now.

Remove generate task for gemspec

---

lib/json/common.rb
tests/json_common_interface_test.rb

Adds `load_file` methods analogous to YAML's.

Add `load_file` and `load_file!` methods, with tests. Fixes issue #386.

---

lib/json.rb
lib/json/common.rb

This move is so that all methods (load, dump, etc.) can refer to the options, not just generate and parse.

Move options from #generate and #parse to common area

---

tests/test_helper.rb

... because it conflicts with test/ruby/test_m17n.rb in ruby/ruby.
An exception `incompatible character encodings: UTF-8 and UTF-16BE`
occurs when:
* a non-existence relative path is added to $LOAD_PATH,
* ASCII-incompatible encoding is set to default_external, and
* some file is loaded.
```
$LOAD_PATH << "no_existing_dir"
Encoding.default_external = Encoding::UTF_16BE
load "dummy.rb" #=> incompatible character encodings: UTF-8 and UTF-16BE
```
This issue can be actually observed by a combination of out-of-place
build and the following command:
make test-all TESTS="json ruby/m17n -n test_object_inspect_external"
http://ci.rvm.jp/logfiles/brlog.trunk-test-random.20200322-221411
ASCII-incompatible default external encoding assumes that the cwd is the
encoding, and it is attempted to …

Do not add a relative path to $LOAD_PATH

---

tests/json_fixtures_test.rb

with `make test-all RUBYOPT=-w`
```
/home/mame/work/ruby/.ext/common/json/common.rb:263: warning: Float 23456789012E666 out of range
```

test/json/json_fixtures_test.rb: Prevent an "out of range" warning

---

lib/json/common.rb

Plus some other minor additions.

Enhance RDoc for JSON.parse

---

ext/json/ext/generator/generator.c
tests/json_generator_test.rb

c34d01ff6a18dac04a90b2e0f820cdb1d5c7e1b2 does not consider US-ASCII compatible but non-UTF-8 encodings, and causes an error in RDoc tests.

Fixed unexpected illegal/malformed utf-8 error

---

java/src/json/ext/Generator.java
json-java.gemspec
json.gemspec

json gemspec requires Ruby 2.x while the -java platform gem does not.
doing so we could also drop some ugly code present due JRuby 1.7 (Ruby 1.9.3) compatibility.
HINT: did some (logical) re-ordering in the gemspec to "match" parts, 
think the gemspec do not need to be separate but keeping things as is, for now.

unify json-java gemspec with the baseline

---

.travis.yml
tests/json_generator_test.rb

an early `return` still caused [ensure to execute](https://github.com/kares/json/blob/1e31f59231d7d31dc58a1e07f228897ddd4b4d7b/tests/json_generator_test.rb#L76),
setting `JSON::SAFE_STATE_PROTOTYPE` constant to `nil` for later tests!

[test] properly 'skip' test on JRuby

---

lib/json/common.rb

Suggest :nodoc: for method recurse_proc.  It's called only (and optionally) by method load, and may not be useful to JSON users.
If we don't :nodoc: this method, it should at least have some tests, which I think are now lacking.

Nodoc for recurse_proc

---

ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h
java/src/json/ext/Generator.java
java/src/json/ext/GeneratorState.java
java/src/json/ext/StringEncoder.java
lib/json/common.rb
lib/json/pure/generator.rb
tests/json_generator_test.rb
tests/json_parser_test.rb

This is a rebase of https://github.com/flori/json/pull/235.
> As per the spec, the forward slash should be escaped in json strings. Not escaping the forward slash causes a security issue when a json object is interpolated inside of a script tag.
> For instance:
```ruby
irb(main):013:0> include ActionView::Helpers::TagHelper
=> Object
irb(main):014:0> include ActionView::Helpers::JavaScriptHelper
=> Object
irb(main):015:0> puts javascript_tag 'var json='+JSON.generate({"key"=>"</script><script>whatever()//"})
<script>
//<![CDATA[
var json={"key":"</script><script>whatever()//"}
//]]>
</script>
```
> In javascript `</script>` has precedence over everything else, so in this case the script tag is terminated and `whatever()` is executed even though it should be part of the string.
> The …

Add an option to escape forward slash character

---

json-java.gemspec
json.gemspec

From https://guides.rubygems.org/specification-reference/#license=
> (...) The full text of the license should be inside of the gem (at the top level) when you build it.
Oddly enough, `json_pure.gemspec` does include the file but not the others.
Also, `json-java.gemspec` called `licenses=` twice.

bundle the LICENSE file in the gem

---

lib/json/common.rb

Complies with https://github.com/ruby/ruby/blob/master/doc/method_documentation.rdoc#argument-description-if-necessary- by removing references to *-convertible thingies.

Partial compliance with doc/method_documentation.rdoc

---

lib/json/common.rb

I presume it's a typo / copy paste overlook.
Introduced in https://github.com/flori/json/commit/33e64ef2 / https://github.com/flori/json/pull/433 cc @marcandre @BurdetteLamar @hsbt

Fix JSON.load_file doc

---

java/src/json/ext/Generator.java
lib/json/pure/generator.rb
tests/json_generator_test.rb

Fix an issue with generate_pretty and empty objects in the Ruby and Java implementations

---

ext/json/ext/parser/extconf.rb
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.h
ext/json/ext/parser/parser.rl
ext/json/extconf.rb
java/src/json/ext/Parser.java
java/src/json/ext/Parser.rl
lib/json/pure/parser.rb
tests/json_parser_test.rb

If set to true all parsed objects will be immediately frozen, and strings will be deduplicated if the Ruby implementation allows it.
This option is useful if you plan to keep the parsed objects around, and want to reduce their memory footprint, and you know they contain duplicated string. It's common in says I18n data, or some database like configuration files (e.g. tax rates etc). 
A similar option was added to YAML/Pysch: https://github.com/ruby/psych/pull/414
MessagePack is also about to have it: https://github.com/msgpack/msgpack-ruby/pull/194 (at least the principle was accepted).
Right now this option incur a small overhead because it has to call `String#-@` through `rb_funcall`, but hopefully Ruby 3.0 should soon expose `rb_fstring_new(const char *ptr, long len) (likely under …

Implement a freeze: parser option

---

json.gemspec

This PR fixes a minor typo in a title in the generated RDoc.

gemspec: Fix a typo in RDoc title

---

ext/json/ext/parser/extconf.rb
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.h
ext/json/ext/parser/parser.rl

Ref: https://bugs.ruby-lang.org/issues/13381
So if all goes well, Ruby 3.0 should expose `rb_enc_interned_str(char* ptr, long len, rb_encoding* enc)`. This function returns an interned string like `String#-@`, except that if the string already exist, it can return it without any allocation.
So for documents with a lot of repeated object keys, or using the `freeze => true` option, this has the potential to very heavily cut down on the number of allocation.
NB: the function doesn't work well on current ruby master, but hopefully https://github.com/ruby/ruby/pull/3786 will make it usable. But I'd like to start the discussion now if possible.

Use `rb_enc_interned_str` if available

---

lib/json.rb

This change fixes an incorrect `#` position in the API documentation of the `JSON` module.
NOTE:
I noticed the incorrect position while I looked into <https://github.com/lsegal/yard/issues/1363>.
Even if this change is merged, <https://www.rubydoc.info/gems/json/JSON> will not show the correct overview.

Fix incorrect `#` position in API doc

---

lib/json/version.rb

originally bumped by https://github.com/flori/json/commit/1942689b6719af1371f54814999d25307696f71c

Bump JSON::VERSION to 2.6.0.

---

tests/json_addition_test.rb

This snuck in while addding tests for the `create_additions`
feature. Caught by JRuby when we added the `limit` option to the
Date/DateTime parsing methods, which causes this to be rejected as
an unknown keyword.

Remove unknown keyword arg from DateTime.parse

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
tests/json_parser_test.rb

When `HAVE_RB_ENC_INTERNED_STR` is enabled it is possible to pass through a null pointer to `rb_enc_interned_str` resulting in a segfault.
Fixes #495
Kudos to @jeremyevans for identifying the fix

Fix parser bug for empty string allocation

---

lib/json/pure/parser.rb
tests/json_parser_test.rb

mixing \u-escaped unicode with literal unicode characters, like so:
```ruby
JSON::Pure::Parser.new(%(["\\u00e9é"])).parse
```
results in this error:
```
.../gems/json-2.3.1/lib/json/pure/parser.rb:194:in `rescue in parse_string': Caught Encoding::CompatibilityError at ']': incompatible character encodings: UTF-8 and ASCII-8BIT (JSON::ParserError)
```
which comes from here:
```
.../gems/json-2.3.1/lib/json/pure/parser.rb:167:in `gsub': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
``` 
I _think_ that forcing the encoding of the gsub result back to ASCII_8BIT is a good fix for this since the StringScanner string is forced to ASCII_8BIT. I can't be entirely certain though; the handling of encoding in this parser is a bit beyond me.

bugfix json/pure mixing escaped with literal unicode raises Encoding::CompatibilityError

---

ext/json/ext/generator/generator.c
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

It makes testing for JSON errors very tedious. You either have to use a Regexp or to regularly update all your assertions when JSON is upgraded.
```
--- expected
+++ actual
@@ -1 +1 @@
-"is invalid JSON: 809: unexpected token at 'FAIL'"
+"is invalid JSON: 859: unexpected token at 'FAIL'"
```
This is what happened to me today and prompted this PR.
cc @nurse @hsbt @tenderlove

Stop including the parser source __LINE__ in exceptions

---

json-java.gemspec
json.gemspec
json_pure.gemspec

GitHub Pages now hosted on `*.github.io`
(I visited https://rubygems.org/gems/json a few days ago, the "homepage" URL was `http://flori.github.com/json/` but it has been fixed now.)

Fix homepage url in gemspec

---

CHANGES.md

Picked up from:
- https://github.com/flori/json/releases/tag/v1.8.6

Add missing changelog entries for 1.8.5 and 1.8.6

---

java/src/json/ext/Generator.java

Always indent even if empty

---

Rakefile

More recent JDKs will reject this command line because 1.6 is too old to build for.

JRuby requires a minimum of Java 8

---

ext/json/ext/generator/generator.c
tests/json_generator_test.rb

The C extension defines an `included` hook for the `JSON::Ext::Generator::GeneratorMethods::String` module but neglects to call `super` in the hook. This can break the functionality of various other code that rely on the fact that `included` on `Module` will always be called.

Call `super` in `included` hook

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

This pull request fixes a small typo in a couple of inline comments. The actual error class is `JSON::ParserError`, not `JSON::ParseError`.

Rename JSON::ParseError to JSON:ParserError

---

lib/json/add/bigdecimal.rb
tests/json_addition_test.rb
tests/json_parser_test.rb

I have a plan to extract `BigDecimal` from stdlib in the future. We need to handle `LoadError` of `BigDecimal` in some tests.

Skip BigDecimal tests when it's missing to load

---

Rakefile

This patch fixes the issue that `rake test` does not actually test
C extension for CRuby.
The `test` task is defined as follows:
https://github.com/flori/json/blob/7ec73ad240d45018f119f5d1a2eaa479ad3f9038/Rakefile#L109-L110
This invokes `:test_pure` and `:test_ext` consecutively.
`:test_pure` assigns `ENV['JSON'] = 'pure'` as follows:
https://github.com/flori/json/blob/7ec73ad240d45018f119f5d1a2eaa479ad3f9038/Rakefile#L97-L98
However, `:test_ext` for CRuby does not change `ENV['JSON']`.
https://github.com/flori/json/blob/7ec73ad240d45018f119f5d1a2eaa479ad3f9038/Rakefile#L252
This lead to `require 'json/pure'` in test_helper.rb, which test only the pure version.
https://github.com/flori/json/blob/7ec73ad240d45018f119f5d1a2eaa479ad3f9038/tests/test_helper.rb#L2-L4
I have added …

Load extension ('json/ext') consistently in test_ext

---

java/src/json/ext/Parser.java
java/src/json/ext/Parser.rl

an alternative PR to: https://github.com/flori/json/pull/543 - for the `BigDecimal` case it should behave the same
main difference is that a custom `opts[:decimal_class]` (e.g. a `BigDecimal` sub-class) should work as before... 
not sure `decimal_class` feature is used much or that folks would set it to anything different than `BigDecimal` but at least the pure.rb seems to [retain a similar logic](https://github.com/flori/json/blob/766f816/lib/json/pure/parser.rb#L214-L222)

[jruby] avoid using deprecated BigDecimal.new

---

.github/workflows/ci.yml
Rakefile

Adding mswin will help with the ruby/ruby 'windows' CI
Windows logs a bunch of junk when running the following in the Rakefile:
```ruby
RAGEL_CODEGEN     = %w[rlcodegen rlgen-cd ragel].find(&which)
RAGEL_DOTGEN      = %w[rlgen-dot rlgen-cd ragel].find(&which)
```
Windows has ragel installed, so added a conditional so it only looks for that...

[CI] Add Windows mswin job

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
tests/json_ext_parser_test.rb

Previously in the JSON::Ext parser, when we encountered an "Infinity" token (and we weren't allowing `NaN`/`Infinity`) we would try to display the "unexpected token" at the character before.
This was found by OSS-Fuzz due to its buffer underflow of exactly 1 byte. Due to low impact this isn't being tracked as a security issue.

Fix "unexpected token" offset for Infinity

---

tests/ractor_test.rb

Require tests/lib/helper.rb to avoid:
NoMethodError: undefined method `assert_separately'
This issue has been seen in Debian and Ubuntu and fixed with the proposed patch.

tests/ractor_test.rb: make assert_separately available

---

CHANGES.md
ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h
java/src/json/ext/Generator.java
java/src/json/ext/GeneratorState.java
java/src/json/ext/StringEncoder.java
lib/json.rb
lib/json/common.rb
lib/json/pure/generator.rb
tests/json_generator_test.rb

Fix: https://github.com/flori/json/pull/215
Fix:https://github.com/flori/json/issues/214
It is rather common to directly interpolate JSON string inside <script> tags in HTML as to provide configuration or parameters to a script.
However this may lead to XSS vulnerabilities, to prevent that 3 characters need to be escaped:
- `/` (forward slash)
- `U+2028` (LINE SEPARATOR)
- `U+2029` (PARAGRAPH SEPARATOR)
The forward slash need to be escaped to prevent closing the script tag early, and the other two are valid JSON but invalid Javascript and can be used to break JS parsing.
Given that the intent of escaping forward slash is the same than escaping U+2028 and U+2029, I chose to rename and repurpose the existing `escape_slash` option.
cc @hsbt @nurse 
This could be used to very [significantly …

Rename escape_slash in script_safe and also escape E+2028 and E+2029

---

ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h
ext/json/ext/parser/parser.c
java/src/json/ext/Generator.java
java/src/json/ext/GeneratorState.java
lib/json/common.rb
lib/json/pure/generator.rb
tests/json_generator_test.rb

The default behavior of calling `to_json` or even `to_s` on unsupported object is problematic in many cases.
```
>> JSON.parse(JSON.dump(Object.new))
=> "#<Object:0x00000001034d8420>"
```
In some cases like blind serailization into some kind of store, you may want to assert that `JSON.parse(JSON.dump(obj)) == obj`.
The `strict` option is a way to ensure this by rejecting any type that doesn't map cleanly to a JSON native type.

Add a `strict` option to Generator

---

lib/json/common.rb
tests/json_generator_test.rb

Fix: https://github.com/flori/json/issues/553
We can never add keyword arguments to `dump` otherwise existing code using unenclosed hash will break.
cc @hsbt

JSON.dump: handle unenclosed hashes regression

---

lib/json/common.rb
tests/json_generator_test.rb

Fixes https://github.com/flori/json/pull/554#issuecomment-1836506784

Overload kwargs in JSON.dump

---

lib/json/common.rb
tests/json_common_interface_test.rb

Fixed this overload
```ruby
dump({}, io, strict: true)
dump({}, limit, strict: true)
```
And fixed this NoMethodError
```ruby
dump({}, strict: true) # => "{}"
JSON.dump({}, strict: true) # => undefined method `merge_dump_options' for JSON:Module
```

Fix JSON.dump overload combination

---

ext/json/ext/generator/generator.c

This avoids pinning an id to the symbol used if a dynamic symbol is passed in as a hash key.
rb_sym2str is available in Ruby 2.2+ and json depends on >= 2.3.

Use rb_sym2str instead of SYM2ID

---

lib/json/add/ostruct.rb
lib/json/generic_object.rb
tests/json_addition_test.rb
tests/json_generic_object_test.rb
tests/json_parser_test.rb

see https://github.com/ruby/ostruct/blob/master/lib/ostruct.rb#L136
`OpenStruct` is not recommend to use with performance reason today. We should make `OpenStruct` support as optional.

Make OpenStruct support as optional

---

ext/json/ext/generator/generator.c

If an exception is raised the FBuffer is leaked.
For example, the following script leaks memory:
```ruby
o = Object.new
def o.to_json(a) = raise
10.times do
100_000.times do
begin
JSON(o)
rescue
end
end
puts `ps -o rss= -p #{$$}`
end
```
Before:
31824
35696
40240
44304
47424
50944
54000
58384
62416
65296
After:
24416
24640
24640
24736
24736
24736
24736
24736
24736
24736

Fix memory leak when exception is raised during JSON generation

---

java/src/json/ext/Parser.java
java/src/json/ext/Parser.rl

These methods have been deprecated for some time and we would like to delete them.
See jruby/jruby#9143 and jruby/jruby#8149.

Remove references to "19" methods in JRuby

---

lib/json/common.rb

Fixes this warning
```
ruby 3.4.0dev (2024-04-03T00:55:24Z master b664590c4d) [x86_64-linux]
/opt/ruby/lib/ruby/3.4.0+0/json/generic_object.rb:3: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0. Add ostruct to your Gemfile or gemspec.
```
```
(press a[TAB])
irb(main):001> a/opt/ruby/lib/ruby/3.4.0+0/json/generic_object.rb:3: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0. Add ostruct to your Gemfile or gemspec.       abort    
alias    
and      
at_exit  
autoload 
autoload?
```

Autoload JSON::GenericObject to avoid require ostruct warning in Ruby 3.4

---

.github/workflows/ci.yml

* https://github.com/oracle/truffleruby/issues/3502 has been fixed.
* Switch to truffleruby-head to get the fix.
See https://github.com/flori/json/pull/575#issuecomment-2014156935

Re-enable truffleruby in CI

---

ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.h
ext/json/ext/parser/parser.rl

The json gem now requires Ruby 2.3, so there is no point keeping compatibility code for older releases that don't have the TypedData API.
cc @hsbt

Cleanup useless ifdef

---

Rakefile
ext/json/ext/generator/extconf.rb
lib/json/ext.rb

* Using the benchmark from https://github.com/flori/json/pull/580
```
$ ruby benchmarks/bench.rb dump pure
JSON::Pure::Generator
truffleruby 24.0.0, like ruby 3.2.2, Oracle GraalVM Native [x86_64-linux]
JSON.dump(obj)   116.000 i/100ms
JSON.dump(obj)   235.000 i/100ms
JSON.dump(obj)   317.000 i/100ms
JSON.dump(obj)   372.000 i/100ms
JSON.dump(obj)   374.000 i/100ms
JSON.dump(obj)      3.735k (± 0.9%) i/s  (267.76 μs/i) -     18.700k in   5.007526s
JSON.dump(obj)      3.738k (± 0.7%) i/s  (267.49 μs/i) -     18.700k in   5.002252s
JSON.dump(obj)      3.743k (± 0.7%) i/s  (267.18 μs/i) -     19.074k in   5.096375s
JSON.dump(obj)      3.747k (± 0.5%) i/s  (266.87 μs/i) -     19.074k in …
```

Use the pure-Ruby generator on TruffleRuby as it is much faster

---

Gemfile
benchmarks/bench.rb
benchmarks/ohai.json

* Restoring benchmarks/ohai.json from dad9fbfbfbfcfe743563348f2c17aedecfabe803.
The commit intended to fix #117, that's still fixed as these new files are not included in the gem `s.files =`.

Add a simple JSON.dump and JSON.load benchmark

---

tests/json_generator_test.rb

test_gc fails when using `bundle exec` because it loads JSON from stdlib. It can be seen by showing the `$LOADED_FEATURES` in the test, without using `bundle exec`. This makes sure we use code from lib and ext when running the fork.
```
test_gc:																															F
================================================================================================================================================================================================================================================================================
Failure: test_gc(JSONGeneratorTest):
pid 58791 exit 1
| /Users/etienne/.gem/ruby/3.3.1/gems/bundler-2.5.16/lib/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated json 2.7.1, but your Gemfile requires json 2.7.2. Since …
```

Use the compiled extension in test

---

ext/json/ext/fbuffer/fbuffer.h
ext/json/ext/generator/generator.c
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

`json` requires Ruby 2.3, so `HAVE_RUBY_ENCODING_H` and `HAVE_RB_ENC_RAISE` are always true.
cc @hsbt

Remove outdated ifdef checks

---

ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h

While profiling `JSON.dump` I noticed a large amount of time is spent validating UTF-8:
Given that we called `rb_enc_str_asciionly_p`, if the string encoding isn't valid UTF-8, we can't know it very cheaply by checking the encoding and coderange that was just computed by Ruby, rather than to do it ourselves.
Also Ruby might have already computed that earlier.
cc @hsbt

JSON.dump: avoid redundant UTF-8 validation

---

ext/json/ext/fbuffer/fbuffer.h

On my `JSON.dump` benchmark it shows up as 6% of runtime, compared to 40% for `convert_UTF8_to_JSON`.
Since the vast majority of the time this function is called we still have some buffer capacity, we might as well check that first and skip the expensive loop etc.
With this change my profiler now report this function as 0.7%, so almost 10x better.

Optimize `fbuffer_inc_capa`

---

ext/json/ext/generator/generator.c

Rather than checking the class we can check the type. This is very subtly different for String subclasses, but I think it's OK.
We also save on checking the type again in the fast path.

Optimize key type check in `json_object_i`

---

lib/json/pure/generator.rb
tests/json_generator_test.rb

Followup: https://github.com/flori/json/pull/519
Fix: https://github.com/flori/json/issues/584

JSON::Pure fix strict mode

---

lib/json/pure/generator.rb
tests/json_generator_test.rb

Fix: #344
This matches the ext behavior.

JSONPure: String#to_json should raise on invalid encoding

---

ext/json/ext/generator/generator.h

This fallback already defined at ruby/internal/stdbool.h

Fix compilation error with C23

---

lib/json/pure/generator.rb

```
* ruby --yjit benchmarks/bench.rb dump pure ruby 3.3.1 (2024-04-23 revision c56cd86388) +YJIT [x86_64-linux]
Before: JSON.dump(obj)    604.604  (± 0.3%) i/s    (1.65 ms/i) -      3.060k in   5.061200s
After:  JSON.dump(obj)      2.531k (± 0.4%) i/s  (395.14 μs/i) -     12.801k in   5.058326s
* ruby benchmarks/bench.rb dump pure
truffleruby 24.1.0-dev-a8ebb51b, like ruby 3.2.2, Oracle GraalVM JVM [x86_64-linux]
Before: JSON.dump(obj)      3.728k (± 9.4%) i/s  (268.26 μs/i) -     18.559k in   5.068915s
After:  JSON.dump(obj)      7.835k (± 8.5%) i/s  (127.63 μs/i) -     39.004k in   5.031116s
```
Using the benchmark from https://github.com/flori/json/pull/580
BTW, the C extension, with YJIT gives:
```
JSON::Ext::Generator
ruby 3.3.1 (2024-04-23 revision c56cd86388) +YJIT [x86_64-linux] …
```

Optimize JSON::Pure::Generator by 2x-4x for simple options cases

---

BSDL
LEGAL

`LICENSE` file mentioned `LEGAL` and `BSDL` files. But this repository didn't have that files.

Added BSDL and LEGAL files same as ruby/ruby

---

ext/json/ext/fbuffer/fbuffer.h
ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h

Extracted from https://github.com/ruby/json/pull/562, this isn't the entirety of the PR, some of the changes are harder to cherry pick and I'll try to get them in followups. The main one missing being https://github.com/ruby/json/pull/562/commits/a81ec4770af4a2f20a9dc06d0295cf5b93a7af91
Before:
```
== Encoding small nested array (121 bytes)
json    91.687k i/100ms
oj   205.309k i/100ms
rapidjson   161.648k i/100ms
json    941.965k (± 1.4%) i/s    (1.06 μs/i) -      4.768M in   5.062573s
oj      2.138M (± 1.2%) i/s  (467.82 ns/i) -     10.881M in   5.091254s
rapidjson      1.678M (± 1.9%) i/s  (596.04 ns/i) - …
```

Various `JSON.generate` optimizations

---

lib/json/common.rb

`JSON.dump` looks terrible on micro-benchmarks because the way it handles arguments is quite allocation heavy compared to the actual JSON generation work.
Profiling the `small hash` benchmarked show 14% of time spent in `Array#compact` and `34%` time spent in `JSON::Ext::GeneratorState.new`. Only `41%` in the actual `generate` function.
By micro-optimizing `JSON.dump`, it can look much better:
Before:
```
== Encoding small nested array (121 bytes)
json    91.687k i/100ms
oj   205.309k i/100ms
rapidjson   161.648k i/100ms
json    941.965k (± 1.4%) i/s    (1.06 μs/i) -      4.768M in   5.062573s
oj      2.138M (± …
```

Optimize JSON.dump argument parsing

---

ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h
lib/json/common.rb
lib/json/ext.rb
lib/json/ext/generator/state.rb

All these methods aren't hotspot and much simpler to implement in Ruby than C. Some code could even be shared with the "pure" implementation but it's not a big deal.
Also this whole "`Generator::State` can be used as a Hash" scream YAGNI, not sure if we want to deprecate it, but definitely something we don't care about optimizing.
Overall this optimize the happy path for instantiating `Generator::State`, which is about half the time spent in micro-benchmarks:
Before:
```
== Encoding small nested array (121 bytes)
json   156.832k i/100ms
oj   209.769k i/100ms
rapidjson   162.922k i/100ms
json      1.599M (± 2.5%) …
```

Migrate some C code to Ruby

---

ext/json/ext/generator/generator.h
ext/json/ext/parser/parser.h

All of these are for rubies older than 2.3.

Get rid of compatibility code for older rubies

---

ext/json/ext/fbuffer/fbuffer.h
ext/json/ext/generator/generator.c
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

All these macros are available on Ruby 2.3+

Get rid of some more outdated compatibility code

---

ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h

Fix: https://github.com/ruby/json/pull/562
This optimization is based on a few assumptions:
- Most strings are ASCII only.
- Most strings had their coderange scanned already.
If the above is true, then by checking the string coderange, we can use a much more streamlined function to encode ASCII strings.
Before:
```
== Encoding twitter.json (466906 bytes)
json   140.000 i/100ms
oj   230.000 i/100ms
rapidjson   108.000 i/100ms
json      1.464k (± 1.4%) i/s  (682.83 μs/i) -      7.420k in   5.067573s
oj      2.338k (± 1.5%) i/s  (427.64 μs/i) -     11.730k in   5.017336s
rapidjson      1.075k (± 1.6%) i/s  (930.40 …
```

Add a fast path for ASCII strings

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
java/src/json/ext/Parser.java
java/src/json/ext/Parser.rl
test/json/json_parser_test.rb

This fixes #529.
In order to avoid changing original encoding,
this patch always dups argument for `ASCII-8BIT` encoding.
I have also added a test `test_argument_encoding_for_binary`.
The structure is following `test_argument_encoding`.
Considering the following facts, IMHO, I believe this patch meets the original intention of this gem.
* `JSON::Pure::Parser.new(str)` does not change the encoding of original argument for `ASCII-8BIT`
* There already exists a test to guarantee that the encoding of argument is not changed for non `ASCII-8BIT` encodings.

Always dup argument to preserve original encoding for force_encoding

---

ext/json/ext/generator/generator.c

Returning state->max_nesting is not valid because it's not a Ruby object.

Fix State#max_nesting=

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.h
ext/json/ext/parser/parser.rl

Extracted from: https://github.com/ruby/json/pull/512
Use `rb_hash_lookup2` to check for hash key existence instead of going through `rb_funcall`.
FYI: @luke-gru

Speedup Parser initialization

---

lib/json/common.rb
test/json/json_common_interface_test.rb

Some Object may return `true` for `respond_to?(:to_str)` but actually return `nil` instead of String when `to_str` is called.
A good example is the Rails encrypted credentials in Rails 7.0, an object called `InheritableOptions` that extends `Hash`.
`InheritableOptions` implements `method_missing` and returns `true` for `respond_to?(:to_str)` but `nil` when actually calling `to_str`.
https://github.com/rails/rails/blob/7-0-stable/activesupport/lib/active_support/ordered_options.rb#L43
Therefore, the following implementation will cause an error.
```rb
h = ActiveSupport::InheritableOptions.new({ a: 1, b: 2 })
h.is_a? Hash #=> true
JSON(h) #=> TypeError: no implicit conversion of nil into String
```
This PR implements strict checking of arguments to avoid this kind of error.

Fix behavior of trying to parse non-string objects

---

lib/json/pure/parser.rb
test/json/json_parser_test.rb

The regex used by `Pure::Parser` for ignoring comments in JSON tries to do some fancy handling to prohibit nested comments, but it causes it to choke on strings that would otherwise be legit (i.e. that can be parsed by `Ext::Parser` or by a C compiler).
For example, a couple strings that are parsed correctly by `Ext::Parser` but not `Pure::Parser`:
This is the original regex (visualized by [Regexper](https://regexper.com/#%28%3F%3A%5C%2F%5C%2F%5B%5E%5Cn%5Cr%5D*%5B%5Cn%5Cr%5D%7C%5C%2F%5C*%28%3F%3A%5B%5E*%5C%2F%5D%7C%5C%2F%5B%5E*%5D%7C%5C*%5B%5E%5C%2F%5D%7C%5C%2F%28%3F%3D%5C*%5C%2F%29%29*%5C*%5C%2F%7C%5B%20%5Ct%5Cr%5Cn%5D%2B%29%2B)):
This is the simplified regex after my changes ([Regexper](https://regexper.com/#%28%3F%3A%5C%2F%5C%2F%5B%5E%5Cn%5Cr%5D*%5B%5Cn%5Cr%5D%7C%5C%2F%5C*%28%3F%3A%5B%5 …

Relax Pure::Parser's comment regex to allow any characters in a multi-line comment

---

Rakefile

No need to be using `jruby` to generate the `java` parser, we should always generate any change regardless of which ruby we're running.

Always generate both parser implementations

---

CHANGES.md
ext/json/ext/generator/generator.h
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
lib/json/common.rb
lib/json/pure/parser.rb

Avoid needless hash allocations and such that degrade performance significantly on micro-benchmarks.

Reduce allocations in `parse` and `load` argument handling

---

CHANGES.md
Rakefile
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
java/src/json/ext/Parser.java
java/src/json/ext/Parser.rl
test/json/json_parser_test.rb

Fix: https://github.com/ruby/json/issues/534
Only include up to 32 bytes of the unparseable source.

Limit the size of ParserError exception messages

---

benchmark/encoder.rb
ext/json/ext/generator/extconf.rb
ext/json/ext/generator/generator.c
ext/json/ext/parser/extconf.rb

If we assume that even UTF-8 strings are mostly ASCII, we can implement a fast path for the ASCII parts.
Before:
```
== Encoding mixed utf8 (20012001 bytes)
ruby 3.4.0dev (2024-10-18T15:12:54Z master d1b5c10957) +YJIT +PRISM [arm64-darwin23]
json     5.000 i/100ms
oj     9.000 i/100ms
rapidjson     2.000 i/100ms
json     49.403 (± 2.0%) i/s   (20.24 ms/i) -    250.000 in   5.062647s
oj    100.120 (± 2.0%) i/s    (9.99 ms/i) -    504.000 in   5.035349s
rapidjson     26.404 (± 0.0%) i/s   (37.87 ms/i) -    132.000 in   5.001025s
Comparison:
json:       49.4 i/s
oj:      100.1 i/s - 2.03x  faster
rapidjson:       26.4 i/s - 1.87x  slower
```
After:
```
== Encoding mixed utf8 (20012001 bytes) …
```

Optimize convert_UTF8_to_JSON for mostly ASCII strings

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
test/json/json_parser_test.rb

Fix: https://github.com/ruby/json/pull/625
Declaring the buffer in a sub block cause bugs on some compilers.

raise_parse_error: avoid UB

---

json.gemspec

* Otherwise the gem always uses the pure-Ruby backend as it's missing that file and rescuing the LoadError.
It'd be great to have some tests with the installed gem or so, but I don't have time to add that (at least not now).

Add lib/json/ext/generator/state.rb to the gemspec

---

ext/json/ext/generator/generator.c
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
lib/json/pure/generator.rb
test/json/json_generator_test.rb

Fix: https://github.com/ruby/json/issues/634
* Related to https://github.com/ruby/json/issues/344

Raise the correct exception in fast_serialize_string

---

ext/json/ext/generator/generator.c
java/src/json/ext/Generator.java
lib/json/pure/generator.rb
test/json/json_generator_test.rb

Fix: https://github.com/ruby/json/issues/437
Before:
```json
{
"foo": {
},
"bar": [
]
}
```
After:
```json
{
"foo": {},
"bar": []
}
```
NB: I'd rather hold on merging this until `2.7.3` has been released, as I'd like to first do a pure fixes and performance release. This can make it into 2.8.0.

pretty_generate: don't apply object_nl / array_nl for empty containers

---

lib/json/pure/parser.rb
test/json/ractor_test.rb

This actually never worked, because the test was always testing the ext version from the stdlib, never the pure version nor the current ext version.

json_pure: fix ractor compatibility

---

CHANGES.md
ext/json/ext/generator/generator.c
lib/json/ext.rb
lib/json/pure/parser.rb
test/json/json_generator_test.rb
test/json/ractor_test.rb
test/json/test_helper.rb

Ref: https://github.com/ruby/json/issues/647
Ref: https://github.com/rubygems/rubygems/pull/6490
Older rubygems are executing `extconf.rb` with a broken `$LOAD_PATH` causing the `json` gem native extension to be loaded with the stdlib version of the `.rb` files.
This fails with
```
json/common.rb:82:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
```
Since this is just for `extconf.rb` we can probably just accept that extra argument and ignore it.
The bug was fixed in rubygems 3.4.9 / 2023-03-20
FYI: @pixeltrix

Workaround rubygems $LOAD_PATH bug

---

CHANGES.md
lib/json/common.rb

Prior to 2.7.3, `JSON::Ext::Parser` would only take kwargs. So if json_pure 2.7.4 is loaded with `json <= 2.7.2` (or stdlib) it blows up.
Ref: https://github.com/ruby/json/issues/650
Fix: https://github.com/ruby/json/issues/651
cc @Hohlen 
NB: make sure this doesn't throw warnings in 2.7 or older.

Instantiate Parser with a kwsplat

---

benchmark/encoder.rb
ext/json/ext/fbuffer/fbuffer.h

Ref: https://github.com/ruby/json/issues/655
Rather than to write the number backward, and then reverse the buffer, we can start from the back of the buffer and write the number in the proper direction.
Before:
```
== Encoding integers (8009 bytes)
json     8.606k i/100ms
oj     9.598k i/100ms
json     86.059k (± 0.8%) i/s   (11.62 μs/i) -    430.300k in   5.000416s
oj     97.409k (± 0.6%) i/s   (10.27 μs/i) -    489.498k in   5.025360s
Comparison:
json:    86058.8 i/s
oj:    97408.8 i/s - 1.13x  faster
```
After:
```
== Encoding integers (8009 bytes)
Warming …
```

Optimize `fbuffer_append_long`

---

ext/json/ext/fbuffer/fbuffer.h
ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.h
ext/json/ext/parser/parser.rl

Ref: https://github.com/ruby/json/issues/655
The actual buffer is still on the heap, but this saves a pair of malloc/free.
This helps a lot on micro-benchmarks
Before:
```
Oj   531.598k i/100ms
JSON reuse   417.666k i/100ms
Oj      5.735M (± 1.3%) i/s  (174.35 ns/i) -     28.706M in   5.005900s
JSON reuse      4.604M (± 1.4%) i/s  (217.18 ns/i) -     23.389M in   5.080779s
Comparison:
Oj:  5735475.6 i/s
JSON reuse:  4604380.3 i/s - 1.25x  slower
```
After:
```
Oj   518.700k i/100ms
JSON reuse   483.370k …
```

Allocate the FBuffer struct on the stack

---

ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h

Fix: https://github.com/ruby/json/issues/460
The various `to_json` methods must rescue exceptions to free the buffer.
```
require 'json'
data = 10_000.times.to_a << BasicObject.new
20.times do
100.times do
begin
data.to_json
rescue NoMethodError
end
end
puts `ps -o rss= -p #{$$}`
end
```
```
20128
24992
29920
34672
39600
44336
49136
53936
58816
63616
68416
73232
78032
82896
87696
92528
97408
102208
107008
111808
```

Fix a memory leak in #to_json methods

---

ext/json/ext/fbuffer/fbuffer.h
ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

Ref: https://github.com/ruby/json/issues/655
Followup: https://github.com/ruby/json/issues/657
Assuming the generator might be used for fairly small documents we can start with a reasonable buffer size of the stack, and if we outgrow it, we can spill on the heap.
In a way this is optimizing for micro-benchmarks, but there are valid use case for fiarly small JSON document in actual real world scenarios, so trashing the GC less in such case make sense.
Before:
```
Oj   518.700k i/100ms
JSON reuse   483.370k i/100ms
Oj      5.722M (± 1.8%) i/s  (174.76 ns/i) -     29.047M in   5.077823s
JSON reuse      5.278M (± 1.5%) i/s …
```

Allocate the initial generator buffer on the stack

---

benchmark/encoder.rb
ext/json/ext/generator/generator.c
ext/json/ext/generator/generator.h
java/src/json/ext/GeneratorState.java
lib/json/common.rb
lib/json/ext/generator/state.rb
lib/json/pure/generator.rb
test/json/json_generator_test.rb

Fix: https://github.com/ruby/json/issues/655
For very small documents, the biggest performance gap with alternatives is
that the API impose that we allocate the `State` object. In a real world app
this doesn't make much of a difference, but when running in a micro-benchmark
this doubles the allocations, causing twice the amount of GC runs, making us
look bad.
However, unless we have to call a `to_json` method, the `State` object isn't
visible, so with some refactoring, we can elude that allocation entirely.
Instead we allocate the State internal struct on the stack, and if we need
to call a `to_json` method, we allocate the `State` and spill the struct on
the heap.
As a result, `JSON.generate` is now as fast as re-using a `State` instance,
as long as only primitives are generated.
Before: …

Elide Generator::State allocation until a to_json method has to be called

---

.github/workflows/ci.yml
Gemfile
Rakefile
test/json/test_helper.rb

Hoping it might find the leak reported in https://github.com/ruby/json/issues/460

Setup ruby_memcheck

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.h
ext/json/ext/parser/parser.rl
java/src/json/ext/Parser.java
java/src/json/ext/Parser.rl
lib/json/common.rb
lib/json/pure/parser.rb
test/json/json_addition_test.rb

Ref: https://bugs.ruby-lang.org/issues/19528
`load` is understood as the default method for serializer kind of libraries, and the default options of `JSON.load` has caused many security vulnerabilities over the years.
The plan is to do like YAML/Psych, deprecate these default options and direct users toward using `JSON.unsafe_load` so at least it's obvious it should be used against untrusted data.

Deprecate unsafe default options of `JSON.load`

---

ext/json/ext/generator/generator.c
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
lib/json/add/bigdecimal.rb
test/json/json_generator_test.rb

Fix: https://github.com/ruby/json/issues/642
Because of it's Ruby 1.8 heritage, the C extension doesn't care much about strings encoding. We should get stricter over time.

Emit warnings when dumping binary strings

---

ext/json/ext/fbuffer/fbuffer.h
ext/json/ext/generator/generator.c
java/src/json/ext/Generator.java
lib/json/pure/generator.rb
test/json/json_generator_test.rb

Fix: https://github.com/ruby/json/issues/667
This is yet another behavior on which the various implementations differed, but the C implementation used to call `to_json` on String subclasses used as keys.
This was optimized out in e125072130229e54a651f7b11d7d5a782ae7fb65 but there is an Active Support test case for it, so it's best to make all 3 implementation respect this behavior.
FYI: @mtasaka

JSON.generate: call to_json on String subclasses

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
lib/json/pure/generator.rb
lib/json/pure/parser.rb
test/json/json_parser_test.rb

From https://github.com/ruby/json/pull/643/files#r1822740241

Add test for parsing broken strings and use String#encode instead of rb_str_conv_enc() in parser

---

ext/json/ext/parser/extconf.rb
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.h
ext/json/ext/parser/parser.rl

If that assumption holds true, then we don't need to copy the
string into a buffer to unescape it. For small string is just saves
copying, but for large ones it also saves a malloc/free combo.
Before:
```
== Parsing twitter.json (567916 bytes)
json    52.000 i/100ms
oj    61.000 i/100ms
oj strict    70.000 i/100ms
Oj::Parser    71.000 i/100ms
rapidjson    55.000 i/100ms
json    510.111 (± 2.9%) i/s    (1.96 ms/i) -      2.548k in   5.000029s
oj    610.232 (± 3.1%) i/s    (1.64 ms/i) -      3.050k in   5.003725s
oj strict    713.231 (± 3.2%) i/s    (1.40 ms/i) -      3.570k in   5.010902s
Oj::Parser    762.598 (± 3.0%) i/s …
```

json_string_unescape: assume the string doesn't need escaping

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

Rather than to copy into a buffer to unescape and then copy that buffer into the final string, we can directly copy into the final string.
The downside is that if the string contains a lot of escaping, we end up returning a string that's larger than strictly necessary, but it's probably fine.
Before:
```
== Parsing twitter.json (567916 bytes)
json    56.000 i/100ms
oj    58.000 i/100ms
oj strict    74.000 i/100ms
Oj::Parser    76.000 i/100ms
rapidjson    52.000 i/100ms
json    556.659 (± 2.9%) i/s    (1.80 ms/i) -      2.800k in   5.034719s
oj    604.077 (± 3.8%) i/s    (1.66 ms/i) -      3.016k in   5.001546s
oj strict …
```

json_string_unescape: Use the returned RString as buffer

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.h
ext/json/ext/parser/parser.rl
java/src/json/ext/Parser.java
java/src/json/ext/Parser.rl
lib/json/common.rb
lib/json/pure/parser.rb

Similar to the optimizations done for the generator, but here it's even simpler because we never need to spill the `Parser` object on the heap.
We also start the parsing buffer with 512B of stack memory, so that in most case no allocations other than the returned value are necessary.
This mostly help on micro-benchmarks, but isn't detrimental to more real world benchmarks.
Before:
```
== Parsing small hash (65 bytes)
json   188.233k i/100ms
oj   213.985k i/100ms
oj strict   242.564k i/100ms
Oj::Parser   448.682k i/100ms
rapidjson   291.925k i/100ms
json      1.983M (± 0.5%) i/s  (504.32 ns/i) -      9.976M in   5.031352s
oj …
```

Elude parser allocation

---

ext/json/ext/fbuffer/fbuffer.h
ext/json/ext/parser/extconf.rb
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

Naively appending elements into RArray or RHash is inneficient because it might cause multiple reallocations and rehasing.
So it's preferable to accumulate all the elements onto a stack, and then use batch APIs to directly create right sized containers.
TODO:
Before:
```
== Parsing activitypub.json (58160 bytes)
json   779.000 i/100ms
oj   799.000 i/100ms
Oj::Parser   953.000 i/100ms
rapidjson   630.000 i/100ms
json      7.989k (± 0.7%) i/s  (125.17 μs/i) -     40.508k in   5.070571s
oj      7.931k (± 1.8%) i/s  (126.09 μs/i) -     39.950k in   5.039171s
Oj::Parser      9.624k (± 0.7%) i/s  (103.91 μs/i) -     48.603k in …
```

Use batch APIs to create Array and Hash objects

---

lib/json/pure/generator.rb
test/json/json_parser_test.rb

* if/elsif comparing `obj.class` is significantly slower: https://github.com/ruby/json/pull/668#issuecomment-2450747190
* The only case where an exact class check is needed so far is for String (https://github.com/ruby/json/issues/667).
* Before:
```
$ ruby -Ilib:ext benchmark/standalone.rb dump pure JSON::Pure::Generator
truffleruby 24.2.0-dev-07b978e4, like ruby 3.2.4, Oracle GraalVM JVM [x86_64-linux] Calculating -------------------------------------
JSON.dump(obj)      6.426k (± 5.9%) i/s  (155.62 μs/i) -     32.395k in   5.064479s
JSON.dump(obj)      6.380k (± 7.4%) i/s  (156.73 μs/i) -     31.806k in   5.021304s
JSON.dump(obj)      6.276k (±10.5%) i/s  (159.33 μs/i) -     31.217k in   5.060762s
JSON.dump(obj)      6.450k (± 7.0%) i/s  (155.05 μs/i) -     32.395k in   5.059538s …
```

Speedup #generate_json by using case/when/end

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
java/src/json/ext/Parser.java
java/src/json/ext/Parser.rl
lib/json/pure/parser.rb
test/json/fixtures/fail4.json
test/json/fixtures/fail9.json
test/json/json_parser_test.rb

Fix: https://github.com/ruby/json/pull/401
Since we already accept comments without even a flag to turn it off, it makes sense to go just one small bit farther and optionally allow trailing comma so we have decent support for what is generally defined as "JSONC" and frequently used for configuration files.

Add option :allow_trailing_comma to JSON#parse

---

ext/json/ext/generator/generator.c
java/src/json/ext/Generator.java
lib/json/pure/generator.rb
test/json/json_generator_test.rb

Followup: https://github.com/ruby/json/pull/633
That's what was raised historically. You could argue that this new exception is more precise, but I've encountered some real production code that expected the old behavior and that was broken by this change.

[2.7.x] Raise JSON::GeneratorError instead of Encoding::UndefinedConversionError

---

ext/json/ext/generator/generator.c

Ignoring `CHAR_BITS` > 8 platform, as far as `ch` indexes `escape_table` that is hard-coded as 256 elements.
```
../../../../src/ext/json/generator/generator.c(121): warning C4333: '>>': right shift by too large amount, data loss
../../../../src/ext/json/generator/generator.c(122): warning C4333: '>>': right shift by too large amount, data loss
../../../../src/ext/json/generator/generator.c(243): warning C4333: '>>': right shift by too large amount, data loss
../../../../src/ext/json/generator/generator.c(244): warning C4333: '>>': right shift by too large amount, data loss
../../../../src/ext/json/generator/generator.c(291): warning C4333: '>>': right shift by too large amount, data loss
../../../../src/ext/json/generator/generator.c(292): warning C4333: '>>': right shift by too large …
```

Fix right shift warnings

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

If we assume most string don't contain any escape sequence we can avoid a lot of costly operations when it holds true.
Before:
```
== Parsing activitypub.json (58160 bytes)
ruby 3.4.0dev (2024-11-06T07:59:09Z precompute-hash-wh.. 7943f98a8a) +YJIT +PRISM [arm64-darwin24]
json   884.000 i/100ms
oj   789.000 i/100ms
Oj::Parser   943.000 i/100ms
rapidjson   584.000 i/100ms
json      8.897k (± 1.3%) i/s  (112.40 μs/i) -     45.084k in   5.068520s
oj      7.967k (± 1.5%) i/s  (125.52 μs/i) -     40.239k in   5.051985s
Oj::Parser      9.564k (± 1.4%) i/s  (104.56 μs/i) -     48.093k in   5.029626s
rapidjson      5.947k (± 1.4%) i/s  (168.16 μs/i) -     29.784k in   5.009437s
Comparison:
json: …
```

parser.rl: parse_string implement a fast path

---

CHANGES.md
lib/json/version.rb

I can still see a lot of inefficiencies in `ext/parser/parser.rl`, but it mostly has to do with how the state machine is implemented, so it might require almost full rewrite.
In the meantime the parser performance progressed enough since `2.7.2` that I'm satisfied enough to not delay the 2.8.0 further, aside from some extra testing. If a brand new parser has to be implemented, that will be for 3.0.
`json` is now faster than `oj` on all three macro-benchmarks, and on par with `Oj::Parser`. It also performs very well on micro-benchmarks.  Full parser benchmark results: https://gist.github.com/casperisfine/cf4b3a0594fae24b7d0eb93daaf3841a
```
== Parsing activitypub.json (58160 bytes)
ruby 3.4.0dev (2024-11-06T07:59:09Z precompute-hash-wh.. 7943f98a8a) +YJIT +PRISM [arm64-darwin24]
Warming up …
```

Release 2.8.0

---

.github/workflows/ci.yml

Fixes Actions warning like:
```text
macos-14 3.2 The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3.
For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default
Show more
```

CI: ci.yml - update to actions/checkout@v4

---

.gitattributes

This way they're hidden in diffs.
It would be good to enforce on CI that the generated files match the source change, however ragel's output isn't consistent across versions and system, so we'll have to rely on changes being noticed by further contributions.

Mark parser.c and Parser.java as generated files

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

Before this commit, we would try to scan for a float, then if that failed, scan for an integer.  But floats and integers have many bytes in common, so we would end up scanning the same bytes multiple times.
This patch combines integer and float scanning machines so that we only have to scan bytes once.  If the machine finds "float parts", then it executes the "isFloat" transition in the machine, which sets a boolean letting us know that the parser found a float.
If we didn't find a float, but we did match, then we know it's an int.
This seems to speed up various benchmarks. Just pulling `citm_catalog.json`,
Before this change:
```
== Parsing citm_catalog.json (1727030 bytes)
ruby 3.4.0dev (2024-11-06T15:34:20Z master 56ecc243e2) +PRISM [arm64-darwin24]
Warming up …
```

Reduce comparisons when parsing numbers

---

CHANGES.md
lib/json/common.rb
test/json/json_common_interface_test.rb

Fix: https://github.com/ruby/json/issues/697
This way even if `Encoding.default_external` is set to a weird value the document will be parsed just fine.

JSON.load_file: explictly load the file as UTF-8

---

benchmark/parser.rb

The documentation state `Oj::Parser.usual` isn't thread safe: https://github.com/ohler55/oj/blob/c70bf4125b546bc7146840b15de36460d42b4dff/ext/oj/parser.c#L1507-L1513
As such we shouldn't benchark it this way, but instantiate a new parser every time. Technically in real world scenarios you could create a pool of parsers and re-use them, but if it's not provided by the gem, I'm not sure we should go out of our way to do it.
@tenderlove

Benchmark `Oj::Parser` in a thread safe way

---

test/json/json_common_interface_test.rb

Found this in ruby ci random failure
```
1) Failure:
TestIRB::ShowDocTest#test_show_doc_without_rdoc [/tmp/ruby/src/trunk-random1/test/irb/test_command.rb:775]:
Expected "" to include "Can't display document because `rdoc` is not installed.\n".
```
The expected warning is suppressed because `$VERBOSE` is changed to nil

Fix $VERBOSE restore

---

ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl

Otherwise the likeliness of seeing that key again is really low, and looking up the cache is just a waste.
Before:
```
== Parsing small hash (65 bytes)
ruby 3.4.0dev (2024-11-13T12:32:57Z fstr-update-callba.. 9b44b455b3) +YJIT +PRISM [arm64-darwin24]
json   343.049k i/100ms
oj   213.943k i/100ms
Oj::Parser    31.583k i/100ms
rapidjson   303.433k i/100ms
json      3.704M (± 1.5%) i/s  (270.01 ns/i) -     18.525M in   5.003078s
oj      2.200M (± 1.1%) i/s  (454.46 ns/i) -     11.125M in   5.056526s
Oj::Parser    285.369k (± 4.8%) i/s    (3.50 μs/i) -      1.453M in   5.103866s
rapidjson      3.216M (± 1.6%) i/s  (310.95 ns/i) -     16.082M in   5.001973s
Comparison:
json:  3703517.4 i/s …
```

Only use the key cache if the Hash is in an Array

---

lib/json/common.rb

ref: #499 
Fixed an inefficiency in the `JSON.[]` method where `to_str` was being called twice unnecessarily. 
- Modified the `JSON.[]` method to reuse the converted string instead of calling `to_str` again
- No functional changes, only performance optimization

Fix redundant to_str call in JSON.[] method

---

Rakefile
ext/json/ext/fbuffer/fbuffer.h
ext/json/ext/generator/generator.c
java/src/json/ext/ByteListDirectOutputStream.java
java/src/json/ext/ByteListTranscoder.java
java/src/json/ext/Generator.java
java/src/json/ext/GeneratorService.java
java/src/json/ext/GeneratorState.java
java/src/json/ext/StringDecoder.java
java/src/json/ext/StringEncoder.java
lib/json/common.rb
lib/json/ext/generator/state.rb
lib/json/truffle_ruby/generator.rb
test/json/json_common_interface_test.rb

Ref: https://github.com/ruby/json/issues/524
Fix: https://github.com/ruby/json/pull/538
Fix: https://github.com/ruby/json/issues/524
Rather than to buffer everything in memory.
Unfortunately Ruby doesn't provide an API to write into and IO without first allocating a string, which is a bit wasteful.
FYI: @headius

JSON.dump: write directly into the provided IO

---

ext/json/ext/generator/generator.c
java/src/json/ext/Generator.java
java/src/json/ext/StringEncoder.java
java/src/json/ext/Utils.java
lib/json/common.rb
lib/json/truffle_ruby/generator.rb
test/json/json_generator_test.rb

Fix: https://github.com/ruby/json/issues/710
Makes it easier to debug why a given tree of objects can't be dumped as JSON.

JSON::GeneratorError expose invalid object

---

ext/json/ext/generator/generator.c

GCC 13 prints the following warning.
https://rubyci.s3.amazonaws.com/ubuntu/ruby-master/log/20241127T001003Z.log.html.gz
```
compiling generator.c
generator.c: In function ‘raise_generator_error’:
generator.c:91:5: warning: function ‘raise_generator_error’ might be a candidate for ‘gnu_printf’ format attribute [-Wsuggest-attribute=format]
91 |     VALUE str = rb_vsprintf(fmt, args);
|     ^~~~~
```
This change prevents the warning by specifying the format attribute.

Prevent a warning of "a candidate for gnu_printf format attribute"

---

ext/json/ext/generator/generator.c
test/json/json_generator_test.rb

Fix: https://github.com/ruby/json/issues/715
The first byte check was missing.

Fix generate(script_safe: true) to not confuse unrelated characters

---

test/json/json_generic_object_test.rb

This is for https://bugs.ruby-lang.org/issues/20309

Refactor to omit JSON::GenericObject tests

---

ext/json/ext/generator/generator.c
java/src/json/ext/GeneratorState.java
lib/json/common.rb
lib/json/ext/generator/state.rb
lib/json/truffle_ruby/generator.rb

It's not necessary as it just delegating from `Generator::State#generate`. We can handle the arity directly in the extension in C or Java, and in Ruby for TruffleRuby.

Remove Generator::State#_generate

---

Rakefile
ext/json/ext/parser/parser.c
ext/json/ext/parser/parser.rl
java/src/json/ext/ParserConfig.java
java/src/json/ext/ParserConfig.rl
java/src/json/ext/ParserService.java
lib/json/common.rb
lib/json/ext.rb
test/json/json_ext_parser_test.rb

Ref: https://github.com/ruby/json/pull/718
The existing `Parser` interface is pretty bad, as it forces to instantiate a new instance for each document.
Instead it's preferable to only take the config and do all the initialization needed, and then keep the parsing state on the stack on in ephemeral memory.
This refactor makes the `JSON::Coder` pull request much easier to implement in a performant way.

Refactor JSON::Ext::Parser to split configuration and parsing state

---

README.md
ext/json/ext/generator/generator.c
lib/json/common.rb
test/json/json_generator_test.rb

To combine JSON fragments to build a bigger JSON document, you can use `JSON::Fragment`:
```ruby
posts_json = cache.fetch_multi(post_ids) do |post_id|
JSON.generate(Post.find(post_id))
end
posts_json.map { |post_json| JSON::Fragment.new(post_json) }
JSON.generate({ posts: posts_json, count: posts_json.count })
```

Introduce JSON::Fragment

---

ext/json/ext/parser/parser.c
test/json/json_parser_test.rb

Fix segmentation fault parsing `"\uaaa"`
```ruby
1000.times { JSON.parse '"\\uaaa"' rescue nil }
```

Fix parsing incomplete unicode escape "\uaaa"

---

ext/json/ext/parser/parser.c
test/json/json_parser_test.rb

Fix parsing these invalid json
```ruby
JSON.parse '1 /*aaa' # => 1, should be error
JSON.parse '1 /' # => never stops
JSON.parse '[1, /' # => never stops
```

Raise parse error on invalid comments

---

README.md
benchmark/encoder.rb
benchmark/parser.rb
ext/json/ext/generator/generator.c
java/src/json/ext/Generator.java
java/src/json/ext/GeneratorState.java
java/src/json/ext/OptionsReader.java
lib/json/common.rb
lib/json/ext/generator/state.rb
lib/json/truffle_ruby/generator.rb
test/json/json_coder_test.rb
test/json/json_generator_test.rb

Since `#to_json` methods are global, it can sometimes be problematic if you need a given type to be
serialized in different ways in different locations.
Instead it is recommended to use the newer `JSON::Coder` API:
```ruby
module MyApp
API_JSON_CODER = JSON::Coder.new do |object|
case object
when Time
object.iso8601(3)
else
object
end
end
end
puts MyApp::API_JSON_CODER.dump(Time.now.utc) # => "2025-01-21T08:41:44.286Z"
```
The provided block is called for all objects that don't have a native JSON equivalent, and
must return a Ruby object that has a native JSON equivalent.

Introduce JSON::Coder

---

README.md
json.gemspec
lib/json/common.rb

Few doc tweaks:
- Also modified the gemspec files' blob as the ragel's `parser.rl` file was removed in c8d5236a921e886b1909081d1a6b907a8d95a249

Few doc tweaks:

---

ext/json/ext/parser/parser.c

On some platforms ctype functions are defined as macros accesing tables. A plain char may be `signed` or `unsigned` per implementations and the extension result implementation dependent.
gcc warns such case:
```
parser.c: In function 'rstring_cache_fetch':
parser.c:138:33: warning: array subscript has type 'char' [-Wchar-subscripts]
138 |     if (RB_UNLIKELY(!isalpha(str[0]))) {
|                              ~~~^~~
parser.c: In function 'rsymbol_cache_fetch':
parser.c:190:33: warning: array subscript has type 'char' [-Wchar-subscripts]
190 |     if (RB_UNLIKELY(!isalpha(str[0]))) {
|                              ~~~^~~
```

Avoid plain char for ctype macros

---

ext/json/ext/generator/generator.c
test/json/json_generator_test.rb

The goal is to be able to dispatch to more optimized search implementations without having to duplicate the escaping code.
Somehow, this is a few % faster already:
```
== Encoding activitypub.json (52595 bytes)
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +YJIT +PRISM [arm64-darwin23]
after     2.257k i/100ms
after     22.930k (± 1.3%) i/s   (43.61 μs/i) -    115.107k in   5.020814s
Comparison:
before:    21604.0 i/s
after:    22930.1 i/s - 1.06x  faster
== Encoding citm_catalog.json (500298 bytes)
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +YJIT +PRISM [arm64-darwin23]
after   137.000 i/100ms
Calculating …
```

Refactor convert_UTF8_to_JSON to split searching and escaping code

---

CHANGES.md
ext/json/ext/generator/generator.c
java/src/json/ext/Generator.java
lib/json/add/symbol.rb
lib/json/truffle_ruby/generator.rb
test/json/json_generator_test.rb

In strict mode we don't need to check for `to_json`, we can just generate a String from a Symbol.
It changes behavior because previously Symbol caused a generator error. But keys in hashes already had support for automatic coercion to String, so it feels ok to do.

Optimize Symbol generation in strict mode

---

CHANGES.md
ext/json/ext/generator/generator.c
java/src/json/ext/GeneratorState.java
java/src/json/ext/OptionsReader.java
lib/json/truffle_ruby/generator.rb
test/json/json_generator_test.rb

Fix: https://github.com/ruby/json/issues/748
`MultiJson` pass `State#to_h` as options, and the `as_json` property defaults to `false` but `false` wasn't accepted by the constructor.

Fix a compatibility issue with `MultiJson.dump(obj, pretty: true)`

---

lib/json/common.rb

I understand there is a compatibility concern here https://github.com/ruby/json/commit/8e0076a3f2f8a7277e659607ab195845ce505a01
However, I'd like to try this out (check CI is passing).

Pass through all options if present.

---

CHANGES.md
ext/json/ext/parser/parser.c
test/json/json_parser_test.rb

Fix: https://github.com/ruby/json/issues/755
Error messages now include a snippet of the document that doesn't parse to help locate the issue, however the way it was done wasn't UTF-8 aware, and it could result in exception messages with truncated characters.
It would be nice to go a bit farther and actually support codepoints, but it's a lot of complexity to do it in C, perhaps if we move that logic to Ruby given it's not a performance sensitive codepath.

Ensure parser error snippets are valid UTF-8

---

lib/json/common.rb
test/json/json_generator_test.rb

Fixes #758 
`Exception#detailed_message` didn't exist until Ruby 3.2. https://bugs.ruby-lang.org/journals/96316/diff?detail_id=61977
https://github.com/ruby/json/pull/712 added `JSON::GeneratorError` which defines `#detailed_message` expecting to delegate to `super`. For affected rubies this leads to `NoMethodError` if invoked, eg as happens [here in sinatra](https://github.com/sinatra/sinatra/blob/c235249abaafa2780b540aca1813dfcf3d17c2dd/lib/sinatra/base.rb#L1272-L1273).

Fix JSON::GeneratorError#detailed_message with Ruby < 3.2

---

java/src/json/ext/Generator.java

This works around a bug in JRuby's IOOutputStream logic whereby an IO with an external encoding will always fail to write incoming bytes. We use base logic to detect if the target object is a "real IO" and if so and it has an external encoding, we drop the realIO and. This causes the rest of IOOutputStream to avoid the fast path and always use dyncall logic with RubyString wrappers.
This works around the issue in jruby/jruby#8682.
This should be temporary, since it will definitely degrade direct writes to such IO objects, but a longer-term fix for the encoding issues spelled out in jruby/jruby#8682 will need to come first, or else json will have to be modified to not use IOOutputStream at all.

Avoid fast-path IO writes when IO has ext enc

---

CHANGES.md
ext/json/ext/parser/parser.c
test/json/json_parser_test.rb

This was the behavior until `2.10.0` unadvertently changed it.
`"\u1"` would raise, but `"\u1zzz"` wouldn't.

Raise a ParserError on all incomplete unicode escape sequence.

---

ext/json/ext/generator/generator.c

https://github.com/ruby/ruby/commit/6b15857e2563cec0b38e6bce7646c1a9abaf4ba3

Removed trailing space

---

ext/json/ext/fbuffer/fbuffer.h
ext/json/ext/generator/depend
ext/json/ext/generator/generator.c
ext/json/ext/vendor/jeaiii-ltoa.h
test/json/json_generator_test.rb

This PR provides an alternative implementation for a long → decimal conversion.
The main difference is that it uses an algorithm pulled from https://github.com/jeaiii/itoa. The source there is C++, it was converted by hand to C for inclusion with this gem. A writeup of this algorithm can be found [here](https://jk-jeon.github.io/posts/2022/02/jeaiii-algorithm/). jeaiii's algorithm is covered by the MIT License, see source code.
On addition this version now also generates the string directly into the `fbuffer`, foregoing the need to run a separate memory copy.
As a result, I see a speedup of 32% on Apple Silicon M1 for an integer set of benchmarks. 
```
== Encoding ints (45025 bytes)
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +YJIT +PRISM [arm64-darwin24]
Warming up …
```

Faster integer formatting

---

CHANGES.md
lib/json/common.rb
test/json/json_common_interface_test.rb

Globally changing the behavior of the library is a bad idea, as many different libraries may rely on `json` and may not expect it and likely never tested that a different default config works for them.
If you need to change the behavior of JSON, it's best to do it only locally, and not globally.
In addition the new `JSON::Coder` interface is much more suited for that.
Another reason for the deprecation is that it's impossible to make `JSON.load` and `JSON.dump` Ractor-safe with such API.

Deprecate all `*_default_options`

---

CHANGES.md
lib/json/common.rb

These were deprecated 16 years ago.

Remove `unparse` and `restore` aliases.

---

java/src/json/ext/GeneratorState.java
java/src/json/ext/RuntimeInfo.java
lib/json/common.rb
lib/json/truffle_ruby/generator.rb

It was only used by JRuby and TruffleRuby to call `SAFE_STATE_PROTOTYPE.dup` instead of `State.new` which isn't an worthy optimization.

Get rid of SAFE_STATE_PROTOTYPE

---

CHANGES.md
ext/json/ext/generator/generator.c
test/json/json_generator_test.rb

We can't directly call `RBASIC_CLASS` as the return value of `to_s` may be an immediate.

Handle non-string keys returning immediate values via `to_s`

---

ext/json/ext/generator/generator.c

This conditional was added with the popcount heuristic as it would call `escape_UTF8_char_basic` for all characters in a chunk even if they didn't need to be escaped. Without that this isn't necessary as `search_escape_basic*` will always return non-zero when `search->ptr` is pointing to a character that needs to be escaped.

Remove unnecessary conditional in escape_UTF8_char_basic.

---

CHANGES.md
ext/json/ext/parser/parser.c
lib/json/common.rb
test/json/json_ext_parser_test.rb
test/json/json_parser_test.rb

The title says it all.
The line and column are also accessible as attributes on the exception object.
NB: this is only for the C version. The Java version would require quite a big refactor and I don't have the time or energy for it.

Improve parser error messages to include line and column numbers

---

ext/json/ext/parser/parser.c
test/json/json_ext_parser_test.rb
test/json/json_parser_test.rb

Report EOF when applicable instead of an empty fragment.
Also stop fragment extraction on first whitespace.

Further improve parsing errors

---

test/json/json_encoding_test.rb

This pull request adds additional tests around JSON encoding and various edge cases.
Some of these edge cases include:
- Deeply nested JSON structures
- Very large strings
- Invalid UTF8 sequences
- Whitespace handling
- Empty objects and arrays
---
related: https://github.com/ruby/ruby/pull/13367

Additional JSON Encoding Test Cases 🧪

---

README.md

When submitting a PR to this project earlier today, I noticed that there weren't really and docs on how to get started quickly. This PR adds some to help with new first-time authors.

update the readme to include bootstrap + testing docs 📚 

---

lib/json/common.rb
lib/json/ext.rb

This pull requests does a few minor tweaks (no behavioral changes) to a few things I noticed when just passing over some files. For example, two files I looked at had a mix of `JSON.parser` and `::JSON.parser` so I made them consistent. Same thing with `JSON::<method>` and `JSON.method`. I just made them consistent in the files I looked at.
If this just seems like a nitpick, feel free to close the PR - I won't be offended.

A few minor consistency changes

---

ext/json/ext/simd/simd.h

I saw a compiler warning when compiling ruby/ruby. This PR attempts to suppress it by making it an inline function, which is usually not warned by `-Wunused-function`.
```
In file included from ../../../../ext/json/parser/parser.c:23:
../../../../ext/json/parser/../simd/simd.h:186:28: warning: ‘find_simd_implementation’ defined but not used [-Wunused-function]
186 | static SIMD_Implementation find_simd_implementation(void) {
|                            ^~~~~~~~~~~~~~~~~~~~~~~~
```
I'm not sure why it's happening (or `HAVE_SIMD` is not defined) on my ruby build, but it does seem unused in parser.c when `HAVE_SIMD` is not defined. So it does seem like a legit warning in some cases.

Suppress -Wunused-function

---

json.gemspec

for https://bugs.ruby-lang.org/issues/21462

Use Dir.glob and base keyword arg for the installer of Ruby package

---

ext/json/ext/simd/simd.h

It's only needed if using GCC `ifunc` mecanism, which we don't.
Ref: https://github.com/ruby/json/pull/743#discussion_r2176537870
cc @nobu

Stop calling `__builtin_cpu_init`

---

Rakefile

Fix: https://github.com/ruby/json/issues/522
When trying to test https://github.com/ruby/json/pull/824 on Windows, I ran into https://github.com/ruby/json/issues/522. The root cause seems to be the path separator is hard-coded to `:` instead of `;` on Windows.
This PR uses `File::PATH_SEPARATOR` as the path separator.

Fix JRuby Java extension build on Windows

---

ext/json/ext/generator/generator.c

Found by wbcheck. This should only be a problem when state is an object rather than stack allocated.
```
WBCHECK ERROR: Missed write barrier detected!
Parent object: 0x7b7b8487c450 (wb_protected: true)
rb_obj_info_dump: 0x00007b7b8487c450 JSON/Generator/State/JSON::Ext::Generator::State JSON/Generator/State
Reference counts - snapshot: 1, writebarrier: 0, current: 6, missed: 5
Missing reference to: 0x7b7b82f35a10
rb_obj_info_dump: 0x00007b7b82f35a10 T_STRING/String  len: 1, capa: 15 "1"
Missing reference to: 0x7b7b82f35e90
rb_obj_info_dump: 0x00007b7b82f35e90 T_STRING/String  len: 1, capa: 15 "2"
Missing reference to: 0x7b7b83629e50
rb_obj_info_dump: 0x00007b7b83629e50 T_STRING/String  len: 1, capa: 15 "3"
Missing reference to: 0x7b7b83b62190
rb_obj_info_dump: 0x00007b7b83b62190 …
```

Fix missing write barrier on Generator State

---

ext/json/ext/simd/simd.h

If `load_uint8x16_4` has an external linkage, it is defined in both `generator` and `parser` extension libraries.
This duplicate symbol causes a linker error when `--with-static-linked-ext` is given, on some platforms.

Functions defined in headers should be `static inline`

---

.github/workflows/ci.yml
.github/workflows/push_gem.yml
Gemfile
Rakefile

Ref: https://github.com/ruby/json/pull/844

Implement automated releases

---

CHANGES.md
lib/json/common.rb
test/json/json_common_interface_test.rb

Commit 73d2137fd3ad18e2a524553e80531f434cf26dde (released with version 2.11.0) removes `JSON.recurse_proc` and its the call in `JSON.load`, opting instead to replace the call with the `:on_load` option. However, this is not the only instance of `recurse_proc`, and anyone using `JSON.unsafe_load` with a proc will receive a `NoMethodError`.
It would appear that `JSON.unsafe_load` had no tests whatsoever, causing this failure. 
These commits: 
1. Add tests covering `JSON.unsafe_load`
2. Align`JSON.unsafe_load` with the current behaviour of `JSON.load`
3. Update the documentation to show that the proc must return the object, as the examples as is do not work.

Fix JSON.unsafe_load with proc argument

---

test/json/json_common_interface_test.rb

`JSONCommonInterfaceTest#test_unsafe_load_default_options` is failed with the following:
```
1) Failure:
JSONCommonInterfaceTest#test_unsafe_load_default_options [/path/to/ruby/test/json/json_common_interface_test.rb:230]:
<2025-09-03 14:28:31.293635 +0200> expected but was
<"2025-09-03 14:28:31 +0200">.
```
I'm not sure why that test is different result with only head version of ruby. I fixed the `Time` object and convert to `String` for assertion.

Backport `JSONCommonInterfaceTest#test_unsafe_load_default_options`

---

test/json/json_generic_object_test.rb

In the Ruby test suite, this test class is causing trouble because ostruct is not available. Having an autoload for `JSON::GenericObject` but causing it not to define the constant causes a warning.
See https://github.com/ruby/ruby/commit/0dc1cd407e7775610f2bcaef6c1282369867f91c and https://github.com/ruby/ruby/commit/caa5d8cdd7483647013af5e3d1701b0ed3ec8785 in ruby.
We can skip defining the test class entirely instead when ostruct is not available.

Better handle missing ostruct

---

Rakefile
test/json/test_helper.rb

Adds branch test coverage when available; Truffle Ruby [does not](https://github.com/oracle/truffleruby/issues/1636) implement branch coverage yet.
Added a couple of comments to warn about common pitfalls using SimpleCov and to explain the oddity of seemingly starting coverage twice.
Also includes SimpleCov config to explicitly include all known files in order to prevent any files silently missed by relying on the implicit discovery system.

Branch coverage & Explicit File Inclusion

---

java/src/json/ext/SWARBasicStringEncoder.java

After thinking about https://github.com/ruby/json/issues/859 and the fix https://github.com/ruby/json/pull/860 all day, something didn't feel quite right. After doing some debugging tonight, I realized the fix might defeat some of the SWAR optimizations. 
When creating the `ByteBuffer` like so `ByteBuffer.wrap(ptrBytes, 0, len)`,  we are looking at a different portion of the `ptrBytes` array when `ptr > 0`. While we end up reading the correct chunk with `bb.getLong(ptr + pos)` or `bb.getInt(ptr + pos)`, we may end up terminating the SWAR-optimized loop early.
Consider:
```
irb(main):001> require "json"
irb(main):002> s = "01234567890"
irb(main):003> JSON.dump(s[2..-1])
ptr: 2
ptrBytes.length: 15
ptrBytes: [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 48, 0, 0, 0, 0]
len: 9
```
The backing …

[Java] implement a better fix for an out of bounds exception

---

java/src/json/ext/SWARBasicStringEncoder.java
test/json/json_encoding_test.rb

Fixes #870
```java
bb = ByteBuffer.wrap(array, offset, length);
bb.getLong(); // Reads from offset and increment offset. ByteBuffer's offset is mutable.
bb.getLong(idx); // Reads from idx, not from offset+idx
bb.getLong(offset + idx); // What we need
```
`array.length` does not match `ptr+len` for a sliced string. Specifying `ptr+len` seems more safe.
`'01234567890123456789"a"b"c"d"e"f"g"h'[20, 15]`
First 15 bytes don't need escape.
15 = 8 + 4 + 3, which can test getLong, getInt and remaining bytes escaping

Fix sliced string escaping
