ruby/json

.travis.yml
rbx-1* is an older config setting.
=> CI with current rbx-2

.travis.yml
Also add a language specification to travis.yml.
More RAM, dedicated cpu cores, awesome network performance, fantastic VM boot times.
> Using our new container-based stack only requires one additional line in your .travis.yml:
> `sudo: false`
Source: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
=> Use the new build env on Travis.

README.md
I would like to propose just few formatting changes in the README file.
=> Update README.md with formatting

Rakefile, json-java.gemspec, json.gemspec, json_pure.gemspec
Just trying to run the tests... The gemspecs are very messy and noisy. This is just a bare minimum.
=> Cleanup gemspec

.travis.yml
... mostly to (current) supported JRubies
=> [CI] setup supported JRubies to test against

lib/json/common.rb
There was no example of load with proc (and there's no test).
=> RDoc for JSON.load with proc

lib/json/common.rb
Fixed at https://github.com/flori/json/issues/458
=> Added backword compatible for < json-2.5

CHANGES.md
Fix: https://github.com/flori/json/issues/479
Restore the `CHANGES.md` file and add entries for the 2.6.0 release.
=> Restore and update changes

.github/workflows/ci.yml
https://github.com/flori/json/actions/runs/7050171470/job/19198749101
=> Exclude truffleruby-head from Actions

ext/json/ext/parser/parser.c, ext/json/ext/parser/parser.rl
They are allocated with ruby_xmalloc, they should be freed with ruby_xfree.
cc @luke-gru
=> Use ruby_xfree to free buffers

lib/json/generic_object.rb
fixup https://github.com/flori/json/pull/565
=> Warn to install ostruct if json couldn't load it

Gemfile
https://github.com/flori/json/actions/runs/9020212654/job/24784934086?pr=586#step:4:102
=> Exclude all_images gem with JRuby

CHANGES.md, README.md, json-java.gemspec, json.gemspec, json_pure.gemspec
Followup up on https://github.com/ruby/json/issues/591.
=> Update all links to the repository following transfert

test/json/json_common_interface_test.rb
Fix: https://github.com/ruby/json/issues/438
=> Add test coverage for JSON.load with a Proc

ext/json/ext/parser/parser.c, ext/json/ext/parser/parser.rl
Closes: https://github.com/ruby/json/pull/512
The last missing piece from that PR, but rebased.
FYI: @luke-gru
=> Ext::Parser avoid costly check on decimal_class when it is nil

benchmark/encoder.rb
- Remove `rapidjson` as it's 2x slower most benchmarks, and on par on a couple of them, so it's not telling us much here.
- Configure `Oj` in `compat` mode so it generate the same JSON on the `many to_json` benchmark.
```
== Encoding small nested array (121 bytes)
json (reuse)   220.202k i/100ms
json   162.190k i/100ms
oj   222.094k i/100ms
json (reuse)      2.322M (± 1.3%) i/s  (430.72 ns/i) -     11.671M in   5.027655s
json      1.707M (± 1.2%) i/s  (585.76 ns/i) -      8.596M in   5.035996s
oj      2.248M (± 1.4%) i/s  (444.94 ns/i) -     11.327M in   5.040712s
Comparison:
json (reuse):  2321686.9 i/s
oj: …
```
=> Encoding benchmark updates

ext/json/ext/generator/generator.c
Followup: 6382c231b0b84abe28cc3a979729a29dd7dba27d
=> Trigger write barrier when setting Generator::State configs

CHANGES.md
I picked from https://github.com/ruby/json/blob/v2.7.x/CHANGES.md
=> Add changes for v2.7.6

ext/json/ext/parser/extconf.rb, ext/json/ext/parser/parser.c, ext/json/ext/parser/parser.rl, test/json/json_addition_test.rb
Warning about deprecation should be categorized as DEPRECATED.
=> Categorize deprecated warning

.github/dependabot.yml
for https://github.com/ruby/json/pull/695
=> Added automated update workflow for GitHub Actions

ext/json/ext/parser/extconf.rb, ext/json/ext/parser/parser.c, ext/json/ext/parser/parser.rl
It's using `rb_gc_mark_maybe` under the hood, which isn't what we need.
=> Stop using `rb_gc_mark_locations`

.github/workflows/ci.yml
Blocked by: https://github.com/ruby/setup-ruby/issues/689
=> Test on aarch64 Ubuntu

lib/json/truffle_ruby/generator.rb
* Using the same logic as in #fast_serialize_string.
* Avoid extra .force_encoding/.b, the input is already a UTF-8 String.
* //n on UTF-8 strings was causing warnings (unless $VERBOSE is nil).
=> Optimize and cleanup JSON::TruffleRuby::Generator.utf8_to_json

ext/json/ext/generator/generator.c, java/src/json/ext/Generator.java, lib/json/truffle_ruby/generator.rb, test/json/json_coder_test.rb
=> Fix JSON::Coder to call as_json proc for NaN and Infinity

ext/json/ext/fbuffer/fbuffer.h, test/json/json_generator_test.rb
https://github.com/ruby/ruby/commit/ee85745c616aa0dcd0bcf207708778a14c02816c
=> Removed trailing spaces

ext/json/ext/vendor/jeaiii-ltoa.h
https://github.com/ruby/json/actions/runs/14124416241/job/39570345675#step:5:19
=> Suppress -Wunknown-pragmas warnings

.github/workflows/ci.yml, ext/json/ext/fbuffer/fbuffer.h, ext/json/ext/generator/extconf.rb, ext/json/ext/generator/generator.c
This would have caught https://github.com/ruby/json/pull/808 on CI.
=> fbuffer.c: add debug mode with bound checks.
